### ISSUE TITLE
ASN 2021-2023

### ISSUE THREAD

**Issue by alberto-antonietti** [alessandropellegrini/risultati-asn#1]
Ciao,

Pensavi di aggiornare il codice per l'ASN 2021-2023?
La ritengo una risorsa molto utile!

Grazie,
Alberto

**Comment by alessandropellegrini** [comment]
Sì vorrei farlo, ma non credo di poter scrivere una patch fino a che non iniziano ad uscire i primi risulati (non ho ancora verificato) perché essendo una nuova tornata potrebbero aver cambiato la logica per recuperare i risultati!

**Comment by alberto-antonietti** [comment]
Ottimo, allora attendiamo i primi risultati. Grazie 😉

**Comment by alessandropellegrini** [comment]
Dovrebbe essere tutto pronto e funzionante :smile:
