### ISSUE TITLE
Elenco completo degli abilitati

### ISSUE THREAD

**Issue by tmontanaro** [alessandropellegrini/risultati-asn#4]
Sapete se per caso esiste un database di tutti gli abilitati degli ultimi X anni?

A livello di sito asn non mi sembra di trovarlo (dovrei essere io a spulciare i singoli risultati uno ad uno), forse però voi li avete collezionati in qualche DB di volta in volta.

Se non è così, si potrebbe pensare di popolare un DB sqlite qui ogni volta che escono dei nuovi risultati,
cosa ne pensate?

**Comment by alessandropellegrini** [comment]
Ciao,
non ho mai implementato quella funzionalità, principalmente per evitare più risonanza di quanta ne vorrei per questo progetto. 

Ricordo di un link con l'elenco di tutti gli abilitati che girò su vari gruppi Facebook, ma ora purtroppo non riesco a ritrovarlo.

**Comment by tmontanaro** [comment]
> Ciao, non ho mai implementato quella funzionalità, principalmente per evitare più risonanza di quanta ne vorrei per questo progetto.
> 
> Ricordo di un link con l'elenco di tutti gli abilitati che girò su vari gruppi Facebook, ma ora purtroppo non riesco a ritrovarlo.

Ok, chiarissimo.
Il link purtroppo non funziona più (era su Uni Molise ma molto probabilmente rinnovando il sito lo hanno rimosso).
Grazie comunque per la risposta. Chiarissimo il motivo per cui non ha collegato un DB. Lasciamo le cose come stanno allora :D
