### ISSUE TITLE
no aggiornamenti su risultati II quadrimestre 2023-2025

### ISSUE THREAD

**Issue by andreaapice** [alessandropellegrini/risultati-asn#8]
sembra stiano iniziando ad uscire i risultati del secondo quadrimestre (e.g. https://asn23.cineca.it/pubblico/miur/esito/12%252FE1/2/2) . La pagina non si aggiorna in automatico?
Tnx

**Comment by alessandropellegrini** [comment]
Grazie di avermi avvisato. No, il passaggio da un quadrimestre all'altro richiede un intervento manuale. Ho riattivato il funzionamento.
